# This is a basic workflow to help you get started with Actions

name: Build the AUR package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron:  '00 00 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#      - name: Arch Linux's package action
#        uses: hapakaien/archlinux-package-action@bugfix/sudoers-user
        
      - name: Install Linux Dependencies
        run: sudo apt-get install -y libgtk-3-dev libssl-dev libasound2-dev
      
#      - name: git clone jpochyla/psst
#        run: git clone https://github.com/jpochyla/psst && cd psst
      - name: Git clone jpochyla/psst
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: jpochyla/psst
          path: psst
        
      - name: Fetch Deps
        run: cargo fetch --locked --target "x86_64-unknown-linux-gnu" --manifest-path psst/Cargo.toml
      
      - name: Build psst
        run: cargo build --frozen --release --all-features --manifest-path psst/Cargo.toml
        
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: psst-gui
          path: psst/target/release/psst-gui

          
      - name: add version to file
        run: cd psst && printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)" > version

      - name: upload version file
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: psst/version

#      - name: Publish AUR package
#        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
#        with:
#          pkgname: psst-git-bin
#          pkgbuild: ./PKGBUILD
#          commit_username: ${{ secrets.AUR_USERNAME }}
#          commit_email: ${{ secrets.AUR_EMAIL }}
#          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
#          commit_message: Update AUR package
#          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
